package app.view.cadastros;

import app.dto.BairroDTO;
import app.interfaces.InterfaceDTO;
import app.interfaces.InterfacePainel;

/**
 *
 * @author S
 */
public class BairroPainel extends InterfacePainel {

    private BairroDTO dto;

    // Construtor padrão
    public BairroPainel() {
        dto = new BairroDTO();
        initComponents();
        setDTO(dto);
    }

    // Construtor com DTO (usado no menu)
    public BairroPainel(InterfaceDTO dto) {
        dto = new BairroDTO(); // Inicializa o DTO no construtor para garantir que não seja nulo (evita NullPointerException)
        initComponents();
        setDTO(dto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(390, 202));

        jLabel1.setText("Nome");
        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    @Override
    public InterfaceDTO getDados() { // metodo getDados é chamado para salvar os dados
        BairroDTO bairroDTO = dto; // Usa a mesma instância do DTO atual que está sendo usado no painel
        bairroDTO.nome = jtfNome.getText(); // Pega o texto do jtfNome e Coloca no nome do dto atual.

        return bairroDTO; //Retorna o dto atualizado para que o Controller use
    }

    @Override
    public void setDTO(InterfaceDTO dto) { //setDTO é chamado para preencher o painel com dados já existentes
        this.dto = (BairroDTO) dto; // Cast - Converte o InterfaceDTO para BairroDTO
        jtfNome.setText(this.dto.nome); // Coloca o valor do nome no campo de texto.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
